---
all:
  children:
    auth_servers:
      hosts:
        auth-ubuntu-01:
          ansible_host: 10.20.30.41
          ansible_port: 22
          ansible_user: ansible
          ansible_become: true
          ansible_python_interpreter: /usr/bin/python3
